steps:
  - id: build-frontend
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - --file=Dockerfile-build
      - "--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA"
      - "--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest"
      - "--cache-from=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest"
      - .

  - id: push-frontend
    name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - --all-tags
      - $_ARTIFACT_REPOSITORY_IMAGE_NAME
    waitFor: ["build-frontend"]

  - id: deploy-product
    name: gcr.io/cloud-builders/gcloud
    args:
      - beta
      - run
      - deploy
      - ectalk-frontend
      - --quiet
      - --platform=managed
      - --project=$PROJECT_ID
      - --region=$_REGION
      - --image=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
      - --service-account=$_SERVICE_ACCOUNT
      - --revision-suffix=$SHORT_SHA
      - --tag=latest
      - --concurrency=40
      - --cpu=1
      - --memory=512Mi
      - --max-instances=3
      - --min-instances=0
      - --no-use-http2
      - --allow-unauthenticated
      - --no-cpu-throttling
      - --ingress=all
      - --set-env-vars=GCP_PROJECT_ID=$PROJECT_ID
    waitFor: ["push-frontend"]

timeout: 2000s
substitutions:
  _REGION: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform
  _SERVICE_ACCOUNT: by-terraform

# ビルド結果に生成したイメージ情報を表示する
# https://cloud.google.com/build/docs/building/build-containers
images:
  - $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
